### ISSUE TITLE
User registration fails after field has been added

### ISSUE THREAD

**Issue by murageden** [andela/wg-bulls#5]
I have added a field `can_create_users` to give user privilege to create a user via API:
```
can_create_users = models.BooleanField(default=False,
                                           editable=True)
    '''
    Flag to mark that the user can create users via api
    '''
```
The application has been running smoothly and then I get an error after user creation has been successful. This is the stack trace:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/wger/core/views/user.py", line 229, in registration
    password)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/contrib/auth/models.py", line 154, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/contrib/auth/models.py", line 148, in _create_user
    user.save(using=self._db)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 745, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/wger/utils/helpers.py", line 82, in wrapper
    signal_handler(*args, **kwargs)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/wger/core/signals.py", line 31, in create_user_profile
    UserProfile.objects.create(user=instance)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/andelandelaa/Projects/wg-bulls/venv-django/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: core_userprofile.can_create_users
```

**Comment by murageden** [comment]
The `BooleanField` field cannot accept NULL values. I used a `NullBooleanField` instead. See the documentation: https://docs.djangoproject.com/en/2.0/ref/models/fields/
